[workspace]
members = [
    "xtask",
    "ch1",
    "ch1-lab",
    "ch2",
    "user",
    "output",
    "syscall",
    "trap-frame",
]
default-members = ["xtask"]

[profile.release]
opt-level = "s"
debug = true
